/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package r.challenge;

import java.io.IOException;

public class App {

    public static void main(String[] args) throws IOException {
        double start = System.nanoTime();
        ChallengeApp app = ChallengeApp
                .builder()
                .filePath("/home/quan/Documents/R-Challenge/app/src/main/resources")
                .inputFile("land.txt")
                .outputFile("out.txt")
                .build();
        app.run();
        double end = System.nanoTime();
        System.out.println("Total time: " + toSecond(start, end));
    }

    private static double toSecond(double nanoTimeStart, double nanoTimeEnd) {
        return (nanoTimeEnd - nanoTimeStart) / 1000000000;
    }
}
