/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package r.challenge;

import java.io.IOException;

public class App {

    private static final String FILE_PATH = "/home/quan/Documents/R-Challenge/app/src/main/resources";
    private static final String INPUT_FILE_NAME = "land.txt";
    private static final String OUTPUT_FILE_NAME = "out.txt";

    public static void main(String[] args) throws IOException {
        double start = System.nanoTime();
        ChallengeApp app = ChallengeApp
                .builder()
                .filePath(FILE_PATH)
                .inputFile(INPUT_FILE_NAME)
                .outputFile(OUTPUT_FILE_NAME)
                .build();
        app.run();
        double end = System.nanoTime();
        System.out.println("Total time: " + toSecond(start, end));
    }

    private static double toSecond(double nanoTimeStart, double nanoTimeEnd) {
        return (nanoTimeEnd - nanoTimeStart) / 1000000000;
    }
}
